'use strict';const assert=require('node:assert/strict'),E=require('../work-design/engine.js');let count=0;const test=(name,fn)=>{fn();count++;};
const revised=()=>{const s=E.sample();s.tasks.forEach(t=>t.active=true);return s;};
test('baseline',()=>{const a=E.analyze(E.sample());assert.deepEqual(a.errors,[]);assert.equal(a.before.demand,2850);assert.equal(a.before.gap,1050);assert.equal(a.saved,0);assert.equal(a.before.capacity,4050);});
test('revised',()=>{const a=E.analyze(revised());assert.equal(a.after.demand,2300);assert.equal(a.saved,550);assert.equal(a.after.gap,450);assert.equal(a.roles.length,1);assert.equal(a.roles[0].skill,'接客');assert.equal(a.roles[0].start,10);assert.equal(a.roles[0].end,13);});
test('remote capacity is not onsite',()=>{const s=revised();s.workers.push({id:'x',name:'遠隔',skills:['事務'],place:'remote',capacity:E.grid({10:60,11:60,12:60})});assert.equal(E.analyze(s).after.gap,450);});
test('onsite front fills gap',()=>{const s=revised();s.workers.push({id:'x',name:'現地',skills:['接客'],place:'onsite',capacity:E.grid({10:60,11:60,12:60})});assert.equal(E.analyze(s).after.gap,0);});
test('same skill but remote cannot do onsite',()=>{const s=revised();s.workers.push({id:'x',name:'遠隔',skills:['接客'],place:'remote',capacity:E.grid({10:60,11:60,12:60})});assert.equal(E.analyze(s).after.gap,450);});
test('moving does not erase time',()=>{const t=E.sample().tasks.find(t=>t.id==='t6');t.active=true;t.after=0;assert.equal(E.effective(t,true).minutes,90);assert.equal(E.effective(t,true).start,13);});
test('essential removal blocked',()=>{let t=E.sample().tasks[0];t.active=true;t.strategy='remove';let r=E.effective(t,true);assert.equal(r.minutes,180);assert.ok(r.blocked);});
test('onsite AI blocked',()=>{let t=E.sample().tasks[0];t.active=true;t.strategy='ai';t.after=15;t.review=5;assert.ok(E.effective(t,true).blocked);});
test('review zero blocked',()=>{let t=E.sample().tasks[2];t.active=true;t.review=0;assert.ok(E.effective(t,true).blocked);});
test('review must fit in total',()=>{let t=E.sample().tasks[2];t.active=true;t.review=20;t.after=15;assert.ok(E.effective(t,true).blocked);});
test('over-window candidate blocked',()=>{let t=E.sample().tasks[2];t.active=true;t.after=90;t.review=10;assert.ok(E.effective(t,true).blocked);});
test('unknown does not become zero',()=>{const s=E.sample();s.tasks[0].evidence='unknown';assert.ok(E.analyze(s).errors.length);});
test('NaN rejects',()=>{const s=E.sample();s.tasks[0].minutes=NaN;assert.ok(E.errors(s).length);});
test('negative rejects',()=>{const s=E.sample();s.tasks[0].minutes=-1;assert.ok(E.errors(s).length);});
test('duplicate tasks rejects',()=>{const s=E.sample();s.tasks[1].id=s.tasks[0].id;assert.ok(E.errors(s).length);});
test('duplicate workers rejects',()=>{const s=E.sample();s.workers[1].id=s.workers[0].id;assert.ok(E.errors(s).length);});
test('empty days rejects',()=>{const s=E.sample();s.tasks[0].days=[];assert.ok(E.errors(s).length);});
test('zero capacity not unknown',()=>{const s=revised();s.workers.forEach(w=>w.capacity=E.grid({}));assert.equal(E.analyze(s).after.gap,2300);});
test('capacity above 60 blocked',()=>{const s=E.sample();s.workers[0].capacity[0][0]=61;assert.ok(E.errors(s).length);});
test('task longer than window blocked',()=>{const s=E.sample();s.tasks[2].minutes=61;assert.ok(E.errors(s).length);});
test('no double capacity across skill',()=>{const s=revised(),a=E.analyze(s);for(const w of s.workers)for(let d=0;d<7;d++)for(let i=0;i<10;i++){const total=a.after.assignments.filter(x=>x.workerId===w.id&&x.day===d&&x.hour===i+8).reduce((x,y)=>x+y.minutes,0);assert.ok(total<=w.capacity[d][i]+1e-6);}});
test('report includes limits and human approval',()=>{let s=revised(),r=E.report(s);assert.match(r,/実現した削減ではない/);assert.match(r,/募集文ではありません/);assert.match(r,/未確認/);assert.match(r,/180日/);});
test('approval invalidates when conditions change',()=>{let s=revised();s.approval={hash:E.fingerprint(s),by:'確認担当',at:'test'};assert.match(E.report(s),/試行計画を確認済み/);s.tasks[0].minutes-=10;assert.match(E.report(s),/まだ正式運用/);});
test('history does not change fingerprint',()=>{let s=revised(),f=E.fingerprint(s);s.history.push({report:'test'});assert.equal(f,E.fingerprint(s));});
test('training overhead separate',()=>{let s=revised(),a=E.analyze(s);s.trainingMinutes+=1000;assert.equal(a.saved,E.analyze(s).saved);assert.match(E.report(s),/1180分/);});
// Deterministic randomized capacity/property tests, not a claims-of-quality metric.
let seed=859;const rand=n=>{seed=(Math.imul(seed,1664525)+1013904223)>>>0;return seed%n;};
for(let k=0;k<50;k++)test('capacity invariant '+k,()=>{const s=revised();s.workers.forEach(w=>w.capacity=w.capacity.map(row=>row.map(v=>rand(61)))) ;s.tasks.forEach(t=>t.active=!!rand(2));const a=E.analyze(s);for(const r of [a.before,a.after]){assert.ok(r.filled<=r.capacity+1e-6);assert.ok(r.filled<=r.demand+1e-6);assert.ok(r.gap>=-1e-6);assert.ok(Math.abs(r.filled+r.gap-r.demand)<1e-6);const used={};for(const x of r.assignments){const w=s.workers.find(w=>w.id===x.workerId),t=r.tasks.find(t=>t.id===x.taskId);assert.ok(w.skills.includes(t.skill));assert.ok(t.place!=='onsite'||w.place==='onsite');assert.ok(t.days.includes(x.day));assert.ok(x.hour>=t.start&&x.hour<t.end);const key=x.workerId+'|'+x.day+'|'+x.hour;used[key]=(used[key]||0)+x.minutes;assert.ok(used[key]<=w.capacity[x.day][x.hour-8]+1e-6);}}});
console.log(JSON.stringify({suite:'engine',passed:count,failed:0}));
