from pathlib import Path
p=Path('work-design/app.js')
s=p.read_text()
s=s.replace("navNames=['相談と業務を集める'", "navNames=['現状業務を確認する'")
s=s.replace('step=0,day=0','step=-1,day=0')
s=s.replace("if(raw){S=validateImport(raw);}","if(raw){S=validateImport(raw);}")
s=s.replace("if(raw.length>300000)throw Error('ファイルは300KBまでです。');","if(raw.length>1000000)throw Error('ファイルは1MBまでです。');")
s=s.replace("return x;}\nfunction persist", "x.intake=window.WDIntake.validate(x.intake);return x;}\nfunction persist")
s=s.replace('Math.max(0,Math.min(5,n))','Math.max(-1,Math.min(5,n))')
s=s.replace("${step?btn('prev'", "${step>-1?btn('prev'")
s=s.replace("$('#nav').innerHTML=navNames.map", "$('#nav').innerHTML=`<button class=\"nav-item ${step===-1?'active':''}\" data-action=\"nav\" data-step=\"-1\" ${step===-1?'aria-current=\"step\"':''}><span class=\"num\">＋</span>今の仕事を集める</button>`+navNames.map")
s=s.replace("if(step===0)html+=home(a);", "if(step===-1)html+=window.WDIntake.render(S);if(step===0)html+=home(a);")
s=s.replace("step=0;});", "step=-1;window.WDIntake.resetTransient();});")
s=s.replace("step=0;render();", "step=-1;window.WDIntake.resetTransient();render();")
s=s.replace("if(f.size>300000)throw Error('ファイルは300KBまでです。');", "if(f.size>1000000)throw Error('ファイルは1MBまでです。');")
s=s.replace("whatIf='none';go(0);toast('読み込みました。", "whatIf='none';window.WDIntake.resetTransient();go(-1);toast('読み込みました。")
# Keep source provenance metadata when the legacy editors save a task/worker.
s=s.replace("const t={id:form.dataset.id,name:fd.get('name').trim()", "const t={...S.tasks.find(t=>t.id===form.dataset.id),id:form.dataset.id,name:fd.get('name').trim()")
s=s.replace("const w={id:form.dataset.id,name:fd.get('name').trim()", "const w={...S.workers.find(w=>w.id===form.dataset.id),id:form.dataset.id,name:fd.get('name').trim()")
s=s.replace("<h3>いま動くもの</h3>","<h3>今の仕事を集める</h3><p class=\"hint\">勤務表のXLSX/CSV、マニュアルの文字入りPDF/DOCX/TXT/MDを端末内で読み取り。元ファイルは送信・保存せず、選んだ抜粋と確認メモを保存します。画像・スキャンPDF、旧Office形式、複雑な勤務記号は非対応。本人・上司の確認後に設計へ追加します。</p><h3>いま動くもの</h3>")
bridge="""window.WDHost={get:()=>S,save:()=>persist(),render,go,toast,modal:openModal,close,download,replace:x=>{S=x;loadError='';persist();},blank:()=>confirmReplace('自社の空の棚卸しに切り替えます。現在の内容が必要なら先に書き出してください。',()=>{S=E.blank();S.intake=window.WDIntakeCore.blank();whatIf='none';step=-1;window.WDIntake.resetTransient();})};
"""
s=s.replace("render();fetch('/api/work-design-ai'",bridge+"render();fetch('/api/work-design-ai'")
p.write_text(s)
p=Path('work-design/index.html')
s=p.read_text().replace("connect-src 'self';","connect-src 'self'; worker-src 'self';")
s=s.replace('./style.css','./style.css?v=1.1.0').replace('<script defer src="./app.js"></script>','<link rel="stylesheet" href="./intake.css?v=1.1.0"><script defer src="./reader.js?v=1.1.0"></script><script defer src="./intake-core.js?v=1.1.0"></script><script defer src="./intake.js?v=1.1.0"></script><script defer src="./app.js?v=1.1.0"></script>')
s=s.replace('v1.0.0','v1.1.0')
p.write_text(s)
