/* Native Chromium / same-origin integration tests, run in GitHub Actions. */
const {chromium}=require(process.env.PLAYWRIGHT_MODULE||'playwright');const assert=require('node:assert/strict'),fs=require('node:fs'),path=require('node:path'),http=require('node:http');
const root=process.cwd(),base=path.join(root,'work-design-intake-build/fixtures');let checks=0;function ok(x,msg){assert.ok(x,msg);checks++;}
(async()=>{const server=http.createServer((req,res)=>{let u=new URL(req.url,'http://localhost');if(u.pathname==='/api/work-design-ai'){res.writeHead(200,{'Content-Type':'application/json'});return res.end('{"enabled":false}');}const p=path.join(root,decodeURIComponent(u.pathname),u.pathname.endsWith('/')?'index.html':'');if(!p.startsWith(root+path.sep)||!fs.existsSync(p)){res.writeHead(404);return res.end();}const ext=path.extname(p);res.writeHead(200,{'Content-Type':{'.js':'text/javascript','.mjs':'text/javascript','.css':'text/css','.html':'text/html','.bcmap':'application/octet-stream'}[ext]||'application/octet-stream'});fs.createReadStream(p).pipe(res);});await new Promise(r=>server.listen(0,'127.0.0.1',r));const url='http://127.0.0.1:'+server.address().port+'/work-design/';const browser=await chromium.launch({headless:true});const context=await browser.newContext({viewport:{width:1440,height:1000}});const p=await context.newPage(),errs=[],external=[];p.on('pageerror',e=>errs.push(e.message));p.on('request',r=>{if(!r.url().startsWith('http://127.0.0.1:')&&!r.url().startsWith('data:'))external.push(r.url());});p.on('dialog',d=>d.accept());try{
await p.goto(url);ok(await p.locator('h1').innerText().then(s=>s.includes('いまの仕事')),'starts with intake');ok(await p.locator('#nav button').count()===7,'legacy six screens retained');await p.screenshot({path:'work-design-intake-build/intake-desktop.png',fullPage:true});
// Existing demo retains its numerical result.
await p.locator('[data-action=nav][data-step="0"]').click();await p.locator('[data-action=start]').click();ok(await p.evaluate(()=>WD.analyze(WDHost.get()).saved)===550,'old demo 550 minutes');await p.locator('[data-action=nav][data-step="-1"]').click();await p.locator('[data-intake=new]').click();await p.locator('#intake-reviewer').fill('確認リーダー');await p.locator('#intake-reviewer').press('Tab');
await p.locator('#intake-shift-file').setInputFiles(path.join(base,'shift.xlsx'));await p.locator('#intake-shift-form').waitFor();ok(await p.locator('#intake-shift-form [name=name]').inputValue()==='0','Excel header mapping');await p.locator('button[form=intake-shift-form]').click();ok(await p.evaluate(()=>WDHost.get().intake.people.length)===2,'Excel produced two role candidates');ok(await p.evaluate(()=>WDHost.get().workers.length)===0,'no implicit staffing transfer');
await p.locator('[data-intake=person-edit]').first().click();ok(await p.locator('[name="c-0-4"]').inputValue()==='0','rest removed');for(const n of ['net','self','boss'])await p.locator('#intake-person-form [name='+n+']').check();await p.locator('button[form=intake-person-form]').click();
await p.locator('#intake-manual-file').setInputFiles(path.join(base,'manual.docx'));await p.locator('#intake-manual-form').waitFor();ok((await p.locator('.intake-lines').innerText()).includes('予約台帳'),'DOCX real text extracted');await p.locator('#intake-manual-form [name=line]').first().check();await p.locator('button[form=intake-manual-form]').click();ok(await p.evaluate(()=>WDHost.get().intake.tasks[0].minutes)===null,'manual has no invented time');ok(await p.evaluate(()=>WDHost.get().tasks.length)===0,'manual not yet workload');
await p.locator('[data-intake=task-edit]').first().click();for(const[k,v]of Object.entries({name:'予約受付',owner:'受付担当',minutes:'30'}))await p.locator('#intake-task-form [name='+k+']').fill(v);for(const[k,v]of Object.entries({start:'9',end:'10',skill:'接客',place:'onsite',evidence:'assumed'}))await p.locator('#intake-task-form [name='+k+']').selectOption(v);await p.locator('#intake-task-form [name=days][value="0"]').check();for(const n of ['self','boss'])await p.locator('#intake-task-form [name='+n+']').check();await p.locator('button[form=intake-task-form]').click();await p.locator('[data-intake=transfer]').click();ok(await p.evaluate(()=>WDHost.get().tasks.length)===1,'reviewed task transferred');ok(await p.evaluate(()=>WDHost.get().workers.length)===1,'only reviewed worker transferred');ok(await p.evaluate(()=>WDHost.get().tasks[0].source.includes('確認リーダー')),'source and reviewer retained');ok(await p.evaluate(()=>WDHost.get().tasks[0].active===false),'no redesign auto activation');ok(await p.evaluate(()=>WD.analyze(WDHost.get()).errors.length)===0,'legacy model accepts intake');
await p.reload();ok(await p.evaluate(()=>WDHost.get().tasks.length)===1,'native localStorage persisted');await p.locator('[data-intake=transfer]').click();ok(await p.evaluate(()=>WDHost.get().tasks.length)===1,'no duplicate on second transfer');
// Real PDF module and Worker, native same-origin asset loading under shipped CSP.
await p.locator('#intake-manual-file').setInputFiles(path.join(base,'manual.pdf'));await p.locator('#intake-manual-form').waitFor({timeout:30000});ok((await p.locator('.intake-lines').innerText()).includes('予約'),'Japanese PDF text extracted');await p.locator('[data-action=close]').click();
await p.locator('#intake-manual-file').setInputFiles(path.join(base,'scanned.pdf'));await p.getByText('この資料は読み取れませんでした',{exact:true}).waitFor();ok((await p.locator('#modal-inner').innerText()).includes('画像・スキャンPDF'),'scan correctly rejected');await p.locator('[data-action=close]').click();
await p.locator('#intake-shift-file').setInputFiles({name:'empty.csv',mimeType:'text/csv',buffer:Buffer.alloc(0)});await p.getByText('この資料は読み取れませんでした',{exact:true}).waitFor();ok((await p.locator('#modal-inner').innerText()).includes('空'),'empty file rejected');await p.locator('[data-action=close]').click();
await p.locator('#intake-manual-file').setInputFiles({name:'xss.txt',mimeType:'text/plain',buffer:Buffer.from('<img src=x onerror="window.hacked=1">\n記録を確認する')});await p.locator('#intake-manual-form').waitFor();ok(await p.locator('.intake-lines img').count()===0,'source rendered as text, not HTML');ok(await p.evaluate(()=>!window.hacked),'no injected command executed');await p.locator('[data-action=close]').click();
// CSV quotation and Shift-JIS support are exercised in reader implementation.
const csv=await p.evaluate(()=>WDReader.csv('担当,曜日\n"担当, A",月'));ok(csv[1][0]==='担当, A','quoted CSV');let bad=false;try{await p.evaluate(()=>WDReader.csv('"unfinished'));}catch{bad=true;}ok(bad,'malformed CSV rejects');
const state=await p.evaluate(()=>JSON.stringify(WDHost.get()));await p.locator('#import-file').setInputFiles({name:'data.json',mimeType:'application/json',buffer:Buffer.from(state)});ok(await p.evaluate(()=>WDHost.get().intake.tasks.length)===1,'portable JSON preserves intake');ok(await p.evaluate(()=>WDHost.get().approval===null),'import requires reapproval');
await p.locator('#import-file').setInputFiles({name:'malicious.json',mimeType:'application/json',buffer:Buffer.from('{"__proto__":{"injected":true}}')});ok(await p.evaluate(()=>!({}).injected),'prototype pollution rejected');ok(await p.evaluate(()=>WDHost.get().tasks.length)===1,'invalid import does not replace work');
await p.setViewportSize({width:390,height:844});await p.screenshot({path:'work-design-intake-build/intake-mobile.png',fullPage:true});ok(await p.evaluate(()=>document.documentElement.scrollWidth<=innerWidth),'mobile no page overflow');ok(errs.length===0,'no browser uncaught exceptions: '+errs.join(';'));ok(external.length===0,'no external file or AI upload: '+external.join(';'));
fs.writeFileSync('work-design-intake-build/native-validation.json',JSON.stringify({suite:'native Chromium / same origin / shipped CSP',passed:checks,failed:0,scope:['XLSX','DOCX','Japanese text PDF real worker','scan refusal','CSV','human confirmation','old calculations','native persistence','JSON roundtrip','XSS','mobile'],ai:'disabled by test endpoint; no live model or Redis tested',publicURL:'not verified by this local-server test'},null,2));console.log('NATIVE E2E PASS '+checks);
}finally{await browser.close();server.close();}})().catch(e=>{console.error(e);process.exit(1);});
