'use strict';const assert=require('node:assert/strict'),C=require('../work-design/intake-core.js');let count=0;const t=(n,f)=>{f();count++;};
const head=['担当','曜日','出勤','退勤','休憩開始','休憩終了','休憩分','技能','場所'],m=C.mapping(head),r=(over=[])=>[['A','月','09:30','15:00','12:00','13:00','60','接客','現地'],...over];
t('maps exact column labels',()=>assert.deepEqual([m.name,m.day,m.start,m.end],[0,1,2,3]));
t('minutes and fractional Excel times',()=>{assert.equal(C.time('09:30'),570);assert.equal(C.time('0.5'),720);assert.equal(C.time('２４：００'),1440);assert.equal(C.time('24:01'),null);assert.equal(C.time('不明'),null);assert.equal(C.time(''),null);});
t('dates and weekdays',()=>{assert.deepEqual(C.day('月曜日'),{day:0,date:null});assert.equal(C.day('2026/09/07').day,0);assert.equal(C.day('2026-02-30'),null);assert.equal(C.monday('2026-09-13'),'2026-09-07');});
t('known rest excluded and half hour kept',()=>{const a=C.shift([head,...r()],m);assert.equal(a.errors.length,0);assert.equal(a.people[0].capacity[0][1],30);assert.equal(a.people[0].capacity[0][4],0);assert.equal(a.people[0].envelope[0][4],0);assert.equal(a.people[0].capacity.flat().reduce((a,b)=>a+b,0),270);});
t('unknown rest never assumed zero',()=>{const x=r();x[0][4]='';x[0][5]='';x[0][6]='';const a=C.shift([head,...x],m);assert.equal(a.people[0].capacity[0][1],'');assert.ok(C.personIssues(a.people[0]).length);});
t('explicit zero rest allowed',()=>{const x=r();x[0][4]='';x[0][5]='';x[0][6]='0';const a=C.shift([head,...x],m);assert.equal(a.people[0].capacity[0][4],60);});
t('overlapping same worker rejected',()=>assert.match(C.shift([head,...r(r())],m).errors.join(''),/重なる/));
t('outside hours rejected, not clipped',()=>{const x=r();x[0][2]='07:00';assert.ok(C.shift([head,...x],m).errors.length);});
t('overnight not collapsed',()=>{const x=r();x[0][2]='17:00';x[0][3]='09:00';assert.ok(C.shift([head,...x],m).errors.length);});
t('missing skill stays unknown',()=>{const x=r();x[0][7]='';const a=C.shift([head,...x],m);assert.equal(a.people[0].skills.length,0);});
t('different weeks filtered explicitly',()=>{const x=r(r());x[0][1]='2026-09-07';x[1][1]='2026-09-14';const a=C.shift([head,...x],m,'2026-09-07');assert.equal(a.excluded,1);assert.equal(a.parsed.length,1);});
t('dates without target week not included',()=>{const x=r();x[0][1]='2026-09-07';assert.equal(C.shift([head,...x],m).people.length,0);});
t('break mismatch blocked',()=>{const x=r();x[0][6]='30';assert.ok(C.shift([head,...x],m).errors.length);});
t('break outside shift blocked',()=>{const x=r();x[0][4]='08:00';assert.ok(C.shift([head,...x],m).errors.length);});
t('null task time not valid',()=>assert.ok(C.taskIssues({name:'A',owner:'B',minutes:null,days:[0],start:9,end:10,skill:'事務',place:'either',evidence:'assumed',mode:'flex'}).includes('実作業の分数')));
t('blank compatible',()=>assert.deepEqual(C.validate(null),C.blank()));
t('malformed intake rejected',()=>assert.throws(()=>C.validate({version:9})));
t('malicious id rejected',()=>{const x=C.blank();x.sources.push({id:'"><img>',name:'A',hash:'x'});assert.throws(()=>C.validate(x));});
t('availability beyond shift rejected',()=>{const a=C.shift([head,...r()],m).people[0];a.netConfirmed=true;a.capacity[0][4]=1;assert.ok(C.personIssues(a).length);});
console.log(JSON.stringify({suite:'intake core',passed:count,failed:0}));
