/* Pure intake rules. Shift availability is not workload. Unknown is never zero. */
(function(root){'use strict';
const DAYS=['月','火','水','木','金','土','日'];
const norm=x=>String(x??'').normalize('NFKC').trim();
const blank=()=>({version:1,sources:[],tasks:[],people:[],reviewer:'',week:'',revision:0});
function time(x){let s=norm(x);if(s==='')return null;if(/^\d*\.\d+$/.test(s)&&+s<1)return Math.round(+s*1440);const m=s.match(/^(\d{1,2})(?::(\d{1,2})|時(?:(\d{1,2})分?)?)?$/);if(!m)return null;const h=+m[1],min=+(m[2]||m[3]||0);return h<=24&&min<60&&(h<24||min===0)?h*60+min:null;}
function day(x){const s=norm(x);const m=s.match(/^([月火水木金土日])(?:曜(?:日)?)?$/);if(m)return{day:DAYS.indexOf(m[1]),date:null};let date;if(/^\d{5}(\.0+)?$/.test(s)){date=new Date(Date.UTC(1899,11,30)+Number(s)*86400000).toISOString().slice(0,10);}else{const m=s.match(/^(\d{4})[\/\-年](\d{1,2})[\/\-月](\d{1,2})日?(?:\s*[（(][月火水木金土日][）)])?$/);if(!m)return null;date=m[1]+'-'+m[2].padStart(2,'0')+'-'+m[3].padStart(2,'0');}const dt=new Date(date+'T00:00:00Z');if(!Number.isFinite(dt.getTime())||dt.toISOString().slice(0,10)!==date)return null;return{day:(dt.getUTCDay()+6)%7,date};}
function monday(date){const d=new Date(date+'T00:00:00Z');if(!Number.isFinite(d.getTime()))return '';d.setUTCDate(d.getUTCDate()-(d.getUTCDay()+6)%7);return d.toISOString().slice(0,10);}
const FIELDS={name:['担当','担当者','氏名','名前','社員名','役割','name'],day:['曜日','日付','勤務日','date','day'],start:['開始','開始時刻','出勤','出勤時刻','始業','start'],end:['終了','終了時刻','退勤','退勤時刻','終業','end'],breakStart:['休憩開始','休憩開始時刻'],breakEnd:['休憩終了','休憩終了時刻'],breakMin:['休憩分','休憩(分)','休憩時間(分)','休憩時間','break'],skill:['技能','担当業務','対応技能','skills'],place:['場所','勤務場所','勤務形態','place']};
function mapping(headers){let m={};for(const [k,list]of Object.entries(FIELDS))m[k]=headers.findIndex(h=>list.includes(norm(h).toLowerCase()));return m;}
function shift(rows,map,week=''){let errors=[],parsed=[],excluded=0;for(let i=1;i<rows.length;i++){const row=rows[i];if(!row.some(x=>norm(x)))continue;const g=k=>map[k]>=0?norm(row[map[k]]):'',name=g('name'),dy=day(g('day')),s=time(g('start')),e=time(g('end'));if(!name||name.length>80){errors.push((i+1)+'行目：担当名を確認してください。');continue;}if(!dy){errors.push((i+1)+'行目：曜日か、年を含む日付を確認してください。');continue;}if(dy.date&&(!week||monday(dy.date)!==week)){excluded++;continue;}if(s===null||e===null||s<480||e>1080||e<=s){errors.push((i+1)+'行目：8:00〜18:00の同日勤務だけが対象です。時刻を確認してください。');continue;}let bs=time(g('breakStart')),be=time(g('breakEnd')),known=bs!==null&&be!==null;if((bs===null)!==(be===null)||known&&(bs<s||be>e||be<=bs)){errors.push((i+1)+'行目：休憩の開始・終了を確認してください。');continue;}if(!known&&g('breakMin')==='0')known=true;const bm=g('breakMin');if(bm&&(!/^\d+$/.test(bm)||+bm>e-s)){errors.push((i+1)+'行目：休憩分は勤務時間内の整数で入力してください。');continue;}if(bs!==null&&bm&&be-bs!==+bm){errors.push((i+1)+'行目：休憩時刻と休憩分が一致しません。');continue;}parsed.push({name,day:dy.day,date:dy.date,start:s,end:e,breakStart:bs,breakEnd:be,known,skill:g('skill'),place:g('place'),row:i+1});}
const groups=new Map();for(const r of parsed){if(!groups.has(r.name))groups.set(r.name,[]);groups.get(r.name).push(r);}let people=[];for(const[name,list]of groups){const cap=Array.from({length:7},()=>Array(10).fill(0)),envelope=cap.map(r=>[...r]),unknown=[];let bad=false;for(let i=0;i<list.length;i++){const r=list[i];if(list.slice(0,i).some(x=>x.day===r.day&&Math.max(x.start,r.start)<Math.min(x.end,r.end))){errors.push(name+'：同じ曜日に重なる勤務があるため、二重計上を防いで停止しました。');bad=true;}for(let h=8;h<18;h++){const presence=Math.max(0,Math.min(r.end,(h+1)*60)-Math.max(r.start,h*60));const knownRest=r.breakStart!==null?Math.max(0,Math.min(r.breakEnd,(h+1)*60)-Math.max(r.breakStart,h*60)):0;envelope[r.day][h-8]+=presence-knownRest;if(!r.known&&presence){cap[r.day][h-8]='';unknown.push('休憩の時刻が未確認');}else if(cap[r.day][h-8]!==''){const rest=r.breakStart!==null?Math.max(0,Math.min(r.breakEnd,(h+1)*60)-Math.max(r.breakStart,h*60)):0;cap[r.day][h-8]+=presence-rest;}}}if(bad)continue;const skills=[...new Set(list.flatMap(r=>r.skill.split(/[、,・/]/).map(norm)).filter(Boolean))],places=[...new Set(list.map(r=>r.place).filter(Boolean))];let place=places.length===1?({'現地':'onsite','現地対応':'onsite','出社':'onsite','onsite':'onsite','遠隔':'remote','在宅':'remote','remote':'remote'}[places[0]]||''):'';people.push({name,capacity:cap,envelope,skills,place,unknown:[...new Set(unknown)],rows:list.map(x=>x.row)});}return{people,errors,excluded,parsed};}
function taskIssues(t){let e=[];if(!norm(t.name)||t.name.length>100)e.push('業務名');if(!norm(t.owner))e.push('担当・役割');if(!Number.isInteger(t.minutes)||t.minutes<1||t.minutes>600)e.push('実作業の分数');if(!Array.isArray(t.days)||!t.days.length||t.days.some(d=>!Number.isInteger(d)||d<0||d>6)||new Set(t.days).size!==t.days.length)e.push('曜日');if(!Number.isInteger(t.start)||!Number.isInteger(t.end)||t.start<8||t.end>18||t.start>=t.end)e.push('時間帯');else if(t.minutes>(t.end-t.start)*60)e.push('時間枠を超える作業');if(!['接客','調理','事務','現場対応','責任者判断','制作'].includes(t.skill))e.push('技能');if(!['onsite','either'].includes(t.place))e.push('場所');if(!['measured','assumed'].includes(t.evidence))e.push('時間の根拠');if(!['flex','coverage'].includes(t.mode))e.push('実施方法');return e;}
function personIssues(p){let e=[];if(!norm(p.name))e.push('担当名');if(!['onsite','remote'].includes(p.place))e.push('場所');if(!p.skills.length||p.skills.some(s=>!['接客','調理','事務','現場対応','責任者判断','制作'].includes(s)))e.push('技能');if(p.capacity.some((r,d)=>r.some((x,h)=>!Number.isInteger(x)||x<0||x>60||x>p.envelope[d][h])))e.push('対象業務に使える分数');if(!p.netConfirmed)e.push('休憩・対象外業務の確認');return e;}
function validate(x){if(!x)return blank();if(x.version!==1||!Array.isArray(x.sources)||x.sources.length>15||!Array.isArray(x.tasks)||x.tasks.length>60||!Array.isArray(x.people)||x.people.length>20||typeof x.reviewer!=='string'||x.reviewer.length>80||typeof x.week!=='string'||JSON.stringify(x).length>260000)throw Error('入口データの形式または容量が不正です。');const validId=v=>typeof v==='string'&&/^[A-Za-z0-9_-]{1,100}$/.test(v);const ids=new Set();for(const s of x.sources){if(!s||!validId(s.id)||ids.has(s.id)||typeof s.name!=='string'||s.name.length>200||typeof s.hash!=='string')throw Error('資料の形式が不正です。');ids.add(s.id);}const draftIds=new Set();for(const t of x.tasks){if(!t||!validId(t.id)||typeof t.name!=='string'||t.name.length>100||typeof t.original!=='string'||t.original.length>2000||typeof t.owner!=='string'||t.owner.length>80||!Array.isArray(t.days)||t.days.length>7||t.days.some(d=>!Number.isInteger(d)||d<0||d>6)||t.minutes!==null&&(!Number.isInteger(t.minutes)||t.minutes<1||t.minutes>600)||t.start!==null&&(!Number.isInteger(t.start)||t.start<8||t.start>17)||t.end!==null&&(!Number.isInteger(t.end)||t.end<9||t.end>18)||typeof t.skill!=='string'||typeof t.place!=='string'||typeof t.note!=='string'||t.note.length>1000)throw Error('業務候補の形式が不正です。');if(draftIds.has(t.id)||!['self','boss'].every(k=>typeof t[k]==='boolean'))throw Error('候補の確認状態が不正です。');draftIds.add(t.id);}const personIds=new Set();for(const p of x.people){if(!p||!validId(p.id)||typeof p.name!=='string'||p.name.length>80||!Array.isArray(p.skills)||p.skills.length>6||!Array.isArray(p.rows)||p.rows.length>250||!Array.isArray(p.unknown))throw Error('勤務候補の形式が不正です。');if(personIds.has(p.id)||!['self','boss','netConfirmed'].every(k=>typeof p[k]==='boolean'))throw Error('勤務候補の確認状態が不正です。');personIds.add(p.id);for(const key of ['capacity','envelope'])if(!Array.isArray(p[key])||p[key].length!==7||p[key].some(r=>!Array.isArray(r)||r.length!==10||r.some(v=>!(key==='capacity'&&v==='')&&(!Number.isInteger(v)||v<0||v>60))))throw Error('勤務時間の形式が不正です。');}return x;}
root.WDIntakeCore={blank,time,day,monday,mapping,shift,taskIssues,personIssues,validate};if(typeof module!=='undefined')module.exports=root.WDIntakeCore;
})(globalThis);
