/* Work intake readers: local-only text/OOXML extraction. No macros or formulas run. */
(function(root){'use strict';
const MAX_FILE=10*1024*1024,MAX_TEXT=60000,MAX_ROWS=250,MAX_COLS=60;
function fail(t){throw Error(t);}
function xml(text){if(/<!DOCTYPE|<!ENTITY/i.test(text))fail('外部参照を含むXMLは読み込めません。');const d=new DOMParser().parseFromString(text,'application/xml');if(d.getElementsByTagName('parsererror').length)fail('文書のXMLが壊れています。');return d;}
function els(n,name){return Array.from(n.getElementsByTagNameNS('*',name));}
function decode(bytes){try{return new TextDecoder('utf-8',{fatal:true}).decode(bytes).replace(/^\uFEFF/,'');}catch{try{return new TextDecoder('shift-jis',{fatal:true}).decode(bytes);}catch{fail('文字コードを読めません。UTF-8のCSV/TXTで保存してください。');}}}
function csv(text){if(text.length>MAX_TEXT)fail('CSV・テキストは6万文字までです。対象の1週間に絞ってください。');const sep=text.split(/\r?\n/)[0].includes('\t')?'\t':',';let rows=[],row=[],v='',q=false;for(let i=0;i<text.length;i++){const c=text[i];if(c==='"'){if(q&&text[i+1]==='"'){v+='"';i++;}else if(q||!v)q=!q;else v+=c;}else if(c===sep&&!q){row.push(v);v='';}else if((c==='\r'||c==='\n')&&!q){if(c==='\r'&&text[i+1]==='\n')i++;row.push(v);if(row.some(x=>x.trim()))rows.push(row);row=[];v='';}else v+=c;if(rows.length>MAX_ROWS||row.length>MAX_COLS)fail('250行・60列までです。対象の部分だけを書き出してください。');}if(q)fail('CSVの引用符が閉じていません。');row.push(v);if(row.some(x=>x.trim()))rows.push(row);if(rows.length>MAX_ROWS||rows.some(r=>r.length>MAX_COLS))fail('250行・60列までです。');return rows;}
function crc32(a){let c=0xffffffff;for(const b of a){c^=b;for(let j=0;j<8;j++)c=(c>>>1)^((c&1)?0xedb88320:0);}return(c^0xffffffff)>>>0;}
async function unzip(buffer){const a=new Uint8Array(buffer),v=new DataView(buffer),u16=p=>v.getUint16(p,true),u32=p=>v.getUint32(p,true);let e=-1;for(let p=a.length-22;p>=Math.max(0,a.length-65557);p--)if(u32(p)===0x06054b50&&p+22+u16(p+20)===a.length){e=p;break;}if(e<0)fail('Office文書の構造を読めません。暗号化や破損を確認してください。');if(u16(e+4)||u16(e+6)||u16(e+8)!==u16(e+10))fail('分割ZIPは非対応です。');const count=u16(e+10);if(count>2500)fail('文書の構造が大きすぎます。');let p=u32(e+16),total=0;const files=new Map();for(let i=0;i<count;i++){if(p+46>a.length||u32(p)!==0x02014b50)fail('Office文書が壊れています。');const flags=u16(p+8),method=u16(p+10),crc=u32(p+16),packed=u32(p+20),size=u32(p+24),nl=u16(p+28),xl=u16(p+30),cl=u16(p+32),offset=u32(p+42);if(p+46+nl+xl+cl>e)fail('不正な文書構造です。');const name=new TextDecoder().decode(a.slice(p+46,p+46+nl));if(name.includes('..')||name.startsWith('/')||name.includes('\\')||files.has(name))fail('安全でない文書パスです。');total+=size;if(total>40*1024*1024||size>8*1024*1024)fail('展開後の文書が大きすぎます。');files.set(name,{flags,method,crc,packed,size,offset});p+=46+nl+xl+cl;}
 return async name=>{const f=files.get(name);if(!f)return null;if(f.flags&1)fail('パスワード付きOffice文書には対応していません。');if(f.size>4*1024*1024)fail('本文や表が大きすぎます。');if(f.offset+30>a.length||u32(f.offset)!==0x04034b50)fail('文書内のデータが壊れています。');const start=f.offset+30+u16(f.offset+26)+u16(f.offset+28);if(start+f.packed>a.length)fail('文書の末尾が欠けています。');let out;if(f.method===0)out=a.slice(start,start+f.packed);else if(f.method===8){if(!root.DecompressionStream)fail('このブラウザではOffice文書を展開できません。CSV/TXTを使ってください。');let stream;try{stream=new Blob([a.slice(start,start+f.packed)]).stream().pipeThrough(new DecompressionStream('deflate-raw'));}catch{fail('このブラウザはOffice文書に非対応です。CSV/TXTに変換してください。');}const reader=stream.getReader(),chunks=[];let len=0;while(true){const x=await reader.read();if(x.done)break;len+=x.value.length;if(len>f.size||len>4*1024*1024){await reader.cancel();fail('文書の展開サイズが不正です。');}chunks.push(x.value);}out=new Uint8Array(len);let at=0;for(const b of chunks){out.set(b,at);at+=b.length;}}else fail('未対応のOffice圧縮形式です。');if(out.length!==f.size||crc32(out)!==f.crc)fail('文書の検証に失敗しました。再保存して試してください。');return new TextDecoder('utf-8',{fatal:true}).decode(out);};}
function colIndex(r){let n=0;for(const c of r.replace(/\d/g,''))n=n*26+c.charCodeAt(0)-64;return n-1;}
async function xlsx(buffer){const get=await unzip(buffer),bookText=await get('xl/workbook.xml'),relText=await get('xl/_rels/workbook.xml.rels');if(!bookText||!relText)fail('Excel（.xlsx）として読めません。');const b=xml(bookText),rels=xml(relText);if(els(b,'workbookPr')[0]?.getAttribute('date1904')==='1')fail('1904年式の日付を使うExcelです。日付を文字列にしてCSVで保存してください。');let shared=[];const ss=await get('xl/sharedStrings.xml');if(ss)shared=els(xml(ss),'si').map(x=>els(x,'t').map(y=>y.textContent).join(''));const sheets=[];for(const sh of els(b,'sheet').slice(0,10)){const id=sh.getAttributeNS('http://schemas.openxmlformats.org/officeDocument/2006/relationships','id')||sh.getAttribute('r:id');const rel=els(rels,'Relationship').find(x=>x.getAttribute('Id')===id);if(!rel||rel.getAttribute('TargetMode')==='External')continue;const target=rel.getAttribute('Target');if(!target||target.includes('..'))fail('Excel内のシート参照が未対応です。');const path=target.startsWith('/')?target.slice(1):'xl/'+target;const text=await get(path);if(!text)continue;let formulas=0;const rows=[];for(const row of els(xml(text),'row')){const arr=[];for(const c of Array.from(row.children).filter(x=>x.localName==='c')){const ci=colIndex(c.getAttribute('r')||'A1');if(ci<0||ci>=MAX_COLS)fail('60列を超えるシートです。');const type=c.getAttribute('t'),val=els(c,'v')[0]?.textContent||'';if(els(c,'f').length){arr[ci]='[数式：値を確認]';formulas++;}else arr[ci]=type==='s'?(shared[Number(val)]??''):type==='inlineStr'?els(c,'t').map(t=>t.textContent).join(''):val;}if(arr.some(x=>String(x||'').trim()))rows.push(Array.from({length:arr.length},(_,i)=>arr[i]||''));if(rows.length>MAX_ROWS)fail('250行を超えるシートです。対象の1週間に絞ってください。');}sheets.push({name:sh.getAttribute('name')||'Sheet',rows,formulas});}if(!sheets.length)fail('読み取れるシートがありません。');return sheets;}
async function docx(buffer){const get=await unzip(buffer),txt=await get('word/document.xml');if(!txt)fail('Word（.docx）として読めません。');const d=xml(txt);for(const n of els(d,'del'))n.remove();const lines=els(d,'p').map(p=>els(p,'t').map(t=>t.textContent).join('')).filter(Boolean);const text=lines.join('\n');if(text.length>MAX_TEXT)fail('本文は6万文字までです。対象部分だけを別ファイルにしてください。');return {text,warnings:['本文と表内の文字だけを抽出します。画像・ヘッダー・コメントは対象外です。変更履歴は挿入を含み、削除済み本文を除きます。']};}
async function pdf(buffer){const lib=await import('./vendor/pdf.min.mjs');lib.GlobalWorkerOptions.workerSrc=new URL('./vendor/pdf.worker.min.mjs',document.baseURI).href;const loading=lib.getDocument({data:new Uint8Array(buffer.slice(0)),isEvalSupported:false,disableFontFace:true,useSystemFonts:true,cMapUrl:new URL('./vendor/cmaps/',document.baseURI).href,cMapPacked:true,enableXfa:false,useWasm:false,stopAtErrors:true});let timer=setTimeout(()=>loading.destroy(),25000);try{const d=await loading.promise;if(d.numPages>30)fail('PDFは30ページまでです。対象のページに分けてください。');let text='',empty=[];for(let p=1;p<=d.numPages;p++){const page=await d.getPage(p),tc=await page.getTextContent();let line='',lastY=null;for(const item of tc.items){if(typeof item.str!=='string')continue;const y=item.transform?.[5];if(lastY!==null&&Math.abs(y-lastY)>3){line+='\n';}else if(line&&!line.endsWith('\n'))line+=' ';line+=item.str;if(item.hasEOL)line+='\n';lastY=y;}if(!line.trim())empty.push(p);text+='【ページ '+p+'】\n'+line.trim()+'\n';if(text.length>MAX_TEXT)fail('PDF本文が6万文字を超えています。対象ページを分けてください。');page.cleanup();}if(empty.length===d.numPages)fail('文字を読み取れません。画像・スキャンPDFは自動読取の対象外です。本文をコピーして貼るか、文字入りPDF/Wordを使ってください。');return {text,warnings:[...(empty.length?['文字を読めないページ：'+empty.join('・')+'。画像内の作業は手で追加してください。']:[]),'PDFの読み順・段組・表は崩れる場合があります。原本を確認してください。']};}finally{clearTimeout(timer);await loading.destroy();}}
async function read(file,kind){if(!file||file.size===0)fail('ファイルが空です。');if(file.size>MAX_FILE)fail('1ファイル10MBまでです。');const ext=file.name.split('.').pop().toLowerCase(),buffer=await file.arrayBuffer();let result;
if(kind==='shift'){if(ext==='xlsx')result={sheets:await xlsx(buffer),warnings:['数式は実行せず、数式セルは要確認として扱います。結合セルの省略値は補いません。']};else if(['csv','tsv','txt'].includes(ext))result={sheets:[{name:'勤務表',rows:csv(decode(buffer)),formulas:0}],warnings:[]};else fail('勤務表はExcel（.xlsx）またはCSV/TSVを選んでください。画像やPDFの勤務表は、対応形式への整理が必要です。');}
else if(ext==='docx')result=await docx(buffer);else if(ext==='pdf')result=await pdf(buffer);else if(['txt','md','csv'].includes(ext)){const text=decode(buffer);if(text.length>MAX_TEXT)fail('本文は6万文字までです。');result={text,warnings:[]};}else fail('マニュアルはPDF・Word（.docx）・TXT・MDを選んでください。.doc、画像は非対応です。');const hash=await crypto.subtle.digest('SHA-256',buffer);return {...result,name:file.name,size:file.size,hash:Array.from(new Uint8Array(hash),b=>b.toString(16).padStart(2,'0')).join('')};}
root.WDReader={read,csv,xlsx,docx,unzip,MAX_TEXT};
})(globalThis);
