from pathlib import Path
from playwright.sync_api import sync_playwright
import os,json,hashlib
URL='https://ruu-first-app.vercel.app/hoiku-ai-check/'
OUT=Path(os.environ.get('HOIKU_VERIFY_OUT','/tmp/hoiku-check-public'));OUT.mkdir(parents=True,exist_ok=True)
KEY='ruu.hoiku-check.v2';checks=[]
def ck(name,ok):
 checks.append({'name':name,'passed':bool(ok)})
 if not ok:raise AssertionError(name)
def action(p,a):p.locator('[data-action="'+a+'"]:visible').first.click();p.wait_for_timeout(70)
def route(p,r):p.evaluate('(r)=>location.hash=r',r);p.wait_for_timeout(80)
def data(p):return p.evaluate('(k)=>JSON.parse(localStorage.getItem(k))',KEY)
try:
 with sync_playwright() as pw:
  b=pw.chromium.launch(headless=True)
  ctx=b.new_context(viewport={'width':1440,'height':1000},accept_downloads=True)
  p=ctx.new_page();errors=[];api_requests=[]
  p.on('pageerror',lambda e:errors.append(str(e)))
  p.on('request',lambda r:api_requests.append(r.url) if r.resource_type in ['xhr','fetch'] else None)
  response=p.goto(URL,wait_until='networkidle',timeout=45000)
  ck('public HTML HTTP 200, no login session',response.status==200)
  ck('bundled release hash matches',hashlib.sha256(response.body()).hexdigest()==json.loads(Path('hoiku-ai-check-v2-build/publish.json').read_text())['sha256'])
  ck('app version is 2.0.0',p.evaluate('HoikuDemoTest.version')=='2.0.0')
  ck('no authentication redirect','vercel.com' not in p.url)
  ck('native storage initially empty',data(p) is None)
  p.screenshot(path=str(OUT/'public-home-desktop.png'),full_page=True)
  action(p,'start');p.locator('#role').select_option('manager');action(p,'next')
  for t in ['comm','billing','safety']:p.locator('input[name="tasks"][value="'+t+'"]').check()
  action(p,'next')
  for t in ['comm','billing','safety']:
   for k,v in {'minutes':'120','burden':'2','mode':'paper','owner':'one','hope':'yes'}.items():p.locator('#a-'+t+'-'+k).select_option(v)
  action(p,'next');p.locator('input[name="goal"][value="people"]').check();action(p,'next')
  ck('storage consent not prechecked',not p.locator('#saveConsent').is_checked())
  p.locator('#saveConsent').check();action(p,'next')
  ck('diagnostic finished',p.locator('.summaryhero').count()==1)
  ck('three kinds shown',all(x in p.locator('#view').inner_text() for x in ['AI活用がおすすめ','ICT・既存ツールで十分','人が対応した方がいい']))
  first=data(p);ck('native result saved once',len(first['results'])==1)
  ck('exact input persisted',first['results'][0]['answers']['comm']['minutes']=='120')
  ck('unknown not fabricated',p.evaluate("HoikuDemoTest.classify('comm',{minutes:'unknown',burden:'unknown',mode:'unknown',owner:'unknown'},'people').minutes") is None)
  p.screenshot(path=str(OUT/'public-result-desktop.png'),full_page=True)
  p.reload(wait_until='networkidle');route(p,'results');action(p,'open-result')
  ck('native reload recovers exact result',data(p)['results'][0]['id']==first['results'][0]['id'] and p.locator('.summaryhero').count()==1)
  ck('reload does not duplicate',len(data(p)['results'])==1)
  action(p,'to-plan');p.locator('#planConfirm').check();action(p,'save-plan')
  ck('native plan saved',len(data(p)['plans'])==1 and bool(data(p)['plans'][0].get('approvalFingerprint')))
  p.reload(wait_until='networkidle');route(p,'results');action(p,'open-result');action(p,'to-plan')
  ck('same plan approval survives reload','端末保存済み' in p.locator('[data-plan-state]').inner_text())
  route(p,'results');p.locator('[data-work="comm"] summary').click();p.locator('#decision-comm').select_option('skip');action(p,'save-result')
  p.reload(wait_until='networkidle');route(p,'results');action(p,'open-result');action(p,'to-plan')
  ck('revised decision invalidates previous approval','確認前' in p.locator('[data-plan-state]').inner_text())
  ck('rejected item absent in plan',p.locator('#plan-owner-comm').count()==0)
  route(p,'results')
  with p.expect_download() as dl:action(p,'export-result')
  dl.value.save_as(str(OUT/'native-result.csv'))
  ck('native CSV download has UTF8 BOM',(OUT/'native-result.csv').read_bytes().startswith(b'\xef\xbb\xbf'))
  route(p,'consult');p.locator('#contact-company').fill('検証専用の架空園');p.locator('#contact-name').fill('テスト担当');p.locator('#contact-email').fill('qa@example.invalid')
  p.locator('#contact-consent').check();p.locator('button[type="submit"]').click();ck('contact requires preview',p.locator('.contact-review').count()==1)
  ck('contact not saved before final confirmation',len(data(p)['leads'])==0)
  action(p,'save-consult');ck('contact saved only on device',len(data(p)['leads'])==1 and data(p)['leads'][0]['email']=='qa@example.invalid')
  p.reload(wait_until='networkidle');route(p,'admin');p.locator('[data-source="admin"][data-value="device"]').click()
  ck('admin reads native saved contact','検証専用の架空園' in p.locator('#view').inner_text())
  p.screenshot(path=str(OUT/'public-admin-desktop.png'),full_page=True)
  route(p,'team');p.screenshot(path=str(OUT/'public-team-desktop.png'),full_page=True)
  ck('synthetic data clearly labeled','架空データ' in p.locator('#view').inner_text())
  p.locator('#companySelect').select_option('DEMO-MORI');ck('small group privacy suppression','それぞれ同じ業務' in p.locator('#view').inner_text())
  action(p,'create-company');p.locator('#companyNickname').fill('検証用の会社');p.locator('#companyForm input[name="consent"]').check();p.locator('#companyForm button[type="submit"]').click();p.wait_for_timeout(120)
  ck('organization code saved',len(data(p)['companies'])==1)
  code=data(p)['companies'][0]['code'];ck('company code format',code.startswith('C-') and len(code)==22)
  ck('sharing limitation visible','同期' in p.locator('#view').inner_text() or '別端末' in p.locator('body').inner_text())
  ck('no AJAX / AI / lead transmission',len(api_requests)==0)
  ck('no desktop JS exceptions',not errors)
  other=b.new_context(viewport={'width':390,'height':844});mobile=other.new_page();mobile_errors=[];mobile.on('pageerror',lambda e:mobile_errors.append(str(e)))
  mobile.goto(URL+'?company='+code+'&industry=hoiku#diagnosis',wait_until='networkidle')
  ck('second device does not inherit private data',data(mobile) is None)
  ck('company-link opens diagnostic',mobile.locator('#role').count()==1)
  route(mobile,'home');mobile.screenshot(path=str(OUT/'public-home-mobile.png'),full_page=True)
  mobile.locator('#menuToggle').click();mobile.locator('[data-route="team"]:visible').first.click();mobile.wait_for_timeout(80)
  ck('mobile navigation works',mobile.locator('#companySelect').count()==1)
  for r in ['home','results','team','plan','measure','consult','admin']:
   route(mobile,r);ck('mobile no horizontal overflow '+r,mobile.evaluate('document.documentElement.scrollWidth<=document.documentElement.clientWidth+1'))
  route(mobile,'home');action(mobile,'sample');mobile.screenshot(path=str(OUT/'public-result-mobile.png'),full_page=True)
  ck('mobile sample results functional',mobile.locator('.summaryhero').count()==1)
  ck('mobile no JS exceptions',not mobile_errors)
  other.close();ctx.close();b.close()
finally:
 report={'url':URL,'scope':'Public HTTPS with fresh unauthenticated Chromium contexts. Native localStorage, reload and actual download. No storage adapter.','checks':checks,'passed':sum(x['passed'] for x in checks),'failed':sum(not x['passed'] for x in checks)}
 (OUT/'browser-verification.json').write_text(json.dumps(report,ensure_ascii=False,indent=2))
 print(json.dumps(report,ensure_ascii=False,indent=2))
