(()=>{
const tasks=[
{id:'newsletter',name:'園だより・クラスだより',desc:'文章作成、季節の挨拶、構成',cat:'ai',weight:5,save:.45},
{id:'parent',name:'保護者への案内文',desc:'行事、持ち物、お願い文',cat:'assist',weight:4,save:.35},
{id:'meeting',name:'職員会議・議事録',desc:'要点、決定事項、担当整理',cat:'ai',weight:5,save:.5},
{id:'recruit',name:'求人・採用広報',desc:'求人票、見学案内、魅力発信',cat:'ai',weight:4,save:.4},
{id:'sns',name:'SNS・園の広報',desc:'投稿文、企画、写真説明',cat:'ai',weight:4,save:.45},
{id:'plans',name:'月案・週案の下書き',desc:'たたき台、表現整理',cat:'assist',weight:3,save:.25},
{id:'handover',name:'引き継ぎ・申し送り',desc:'情報の要約、抜け漏れ整理',cat:'assist',weight:3,save:.25},
{id:'incident',name:'ヒヤリハットの整理',desc:'分類、傾向、再発防止の材料',cat:'assist',weight:3,save:.2},
{id:'shift',name:'勤務シフト',desc:'人数、勤務条件、配置',cat:'system',weight:2,save:.15},
{id:'billing',name:'請求・勤怠・登降園',desc:'正確な記録、集計、連携',cat:'system',weight:1,save:.1},
{id:'complaint',name:'難しい保護者対応',desc:'状況整理、文案のたたき台',cat:'human',weight:2,save:.1},
{id:'safety',name:'事故・健康・安全判断',desc:'子どもの安全に関する最終判断',cat:'human',weight:0,save:0}
];
const tools=[['paper','紙・手書きが多い'],['excel','Excel・Word中心'],['line','LINE・チャットで情報共有'],['ict','保育ICTシステム導入済み'],['templates','園独自の書式・テンプレあり'],['rules','文章は園長・主任の確認が必要']];
const goals=[['time','職員の事務時間を減らしたい'],['quality','文章・記録の質をそろえたい'],['recruit','採用・広報を強くしたい'],['handover','属人化・引き継ぎを減らしたい']];
const app=document.getElementById('app'), form=document.getElementById('checkForm'), steps=[...document.querySelectorAll('.step')], results=document.getElementById('results');
let current=1,lastDiagnosis=null;
const taskGrid=document.getElementById('taskGrid');
tasks.forEach(t=>taskGrid.insertAdjacentHTML('beforeend',`<label class="task"><input type="checkbox" name="task" value="${t.id}"><span><strong>${t.name}</strong><small>${t.desc}</small></span></label>`));
const toolGrid=document.getElementById('toolGrid');tools.forEach(([id,label])=>toolGrid.insertAdjacentHTML('beforeend',`<label class="task"><input type="checkbox" name="tool" value="${id}"><span><strong>${label}</strong><small>当てはまる場合に選択</small></span></label>`));
const goalGrid=document.getElementById('goalGrid');goals.forEach(([id,label],i)=>goalGrid.insertAdjacentHTML('beforeend',`<label class="task"><input type="radio" name="goal" value="${id}" ${i===0?'checked':''}><span><strong>${label}</strong><small>優先順位の調整に使用</small></span></label>`));
const hours=document.getElementById('hours'),hoursOut=document.getElementById('hoursOut');hours.addEventListener('input',()=>hoursOut.textContent=`${hours.value}時間/週`);
function showStep(n){current=n;steps.forEach((s,i)=>s.classList.toggle('hidden',i!==n-1));document.getElementById('backBtn').disabled=n===1;document.getElementById('nextBtn').textContent=n===4?'診断する':'次へ';document.getElementById('progressBar').style.width=`${n*25}%`;app.scrollIntoView({behavior:'smooth',block:'start'});}
document.getElementById('nextBtn').addEventListener('click',()=>{if(current===2&&!document.querySelector('input[name="task"]:checked')){document.getElementById('taskError').classList.remove('hidden');return;}document.getElementById('taskError').classList.add('hidden');if(current<4)showStep(current+1);else diagnose();});
document.getElementById('backBtn').addEventListener('click',()=>{if(current>1)showStep(current-1)});
function val(name){const el=document.querySelector(`[name="${name}"]:checked`);return el?el.value:''}function vals(name){return [...document.querySelectorAll(`[name="${name}"]:checked`)].map(x=>x.value)}
function diagnose(){const selectedIds=vals('task'),selected=tasks.filter(t=>selectedIds.includes(t.id)),toolVals=vals('tool'),goal=val('goal')||'time';let base=selected.reduce((a,t)=>a+t.weight,0);if(toolVals.includes('paper'))base+=5;if(toolVals.includes('excel'))base+=3;if(toolVals.includes('ict'))base-=2;if(goal==='time')base+=3;if(goal==='quality')base+=2;let score=Math.max(25,Math.min(92,Math.round(35+base*2.2)));
const goalBoost={time:['meeting','newsletter','sns'],quality:['parent','plans','handover'],recruit:['recruit','sns','newsletter'],handover:['meeting','handover','incident']}[goal];
const ranked=[...selected].sort((a,b)=>(b.weight+(goalBoost.includes(b.id)?2:0))-(a.weight+(goalBoost.includes(a.id)?2:0)));
const groups={ai:[],assist:[],system:[],human:[]};ranked.forEach(t=>groups[t.cat].push(t));
const weekly=Number(hours.value);const saveRatio=Math.min(.58,ranked.reduce((s,t)=>s+t.save,0)/Math.max(1,ranked.length));const saveHours=Math.max(.5,Math.round(weekly*saveRatio*2)/2);const top=ranked[0]||tasks[0];
lastDiagnosis={score,groups,top,saveHours,selected,toolVals,goal,name:document.getElementById('nurseryName').value.trim()||'御園'};
renderResults(lastDiagnosis);form.classList.add('hidden');results.style.display='block';document.getElementById('progressBar').style.width='100%';app.scrollIntoView({behavior:'smooth',block:'start'});}
function renderResults(d){document.getElementById('score').textContent=d.score;document.getElementById('scoreRing').style.background=`conic-gradient(var(--brand) ${d.score*3.6}deg,#e6efed 0)`;document.getElementById('resultTitle').textContent=`${d.name}は「まず1〜2業務」から始めるのがおすすめです`;document.getElementById('resultLead').textContent='全部をAI化する必要はありません。効果が見えやすく、職員が確認しやすい仕事から小さく試すと進めやすいです。';document.getElementById('quickCount').textContent=d.groups.ai.length;document.getElementById('saveHours').textContent=`約${d.saveHours}h`;document.getElementById('topPriority').textContent=shortName(d.top.name);
const configs=[['ai','今すぐAIで試す','cat-ai','文章の下書き・要約・案出しなど、結果を人が確認できる仕事。'],['assist','AIは補助だけ','cat-assist','AIに全部任せず、下書きや整理まで。職員が内容を確認します。'],['system','通常システム向き','cat-system','正確な計算・記録・権限管理が中心。AIより既存ICTや通常システムを優先。'],['human','人が判断する','cat-human','安全・健康・難しい対人判断など、最終判断をAIへ渡さない仕事。']];
const grid=document.getElementById('categoryGrid');grid.innerHTML='';configs.forEach(([key,title,cls,desc])=>{const items=d.groups[key];grid.insertAdjacentHTML('beforeend',`<div class="category ${cls}"><h3>${title}</h3><div class="help">${desc}</div>${items.length?items.map(t=>`<div class="result-item"><strong>${t.name}<span class="pill">${key==='ai'?'優先候補':key==='assist'?'確認必須':key==='system'?'ICT優先':'人が主役'}</span></strong><div class="why">${reason(t,key)}</div></div>`).join(''):'<div class="result-item"><div class="why">今回選ばれた業務では該当なし</div></div>'}</div>`)});
const choices=document.getElementById('demoChoices');choices.innerHTML='';d.selected.slice(0,4).forEach((t,i)=>{const b=document.createElement('button');b.type='button';b.className='demo-choice'+(i===0?' active':'');b.textContent=t.name;b.addEventListener('click',()=>{document.querySelectorAll('.demo-choice').forEach(x=>x.classList.remove('active'));b.classList.add('active');showDemo(t)});choices.appendChild(b)});showDemo(d.top);}
function reason(t,key){if(key==='ai')return 'たたき台を早く作り、人が直して使えるため。';if(key==='assist')return '文脈や園の方針が重要なので、AIは整理・下書きまで。';if(key==='system')return '重複防止、正確な計算、記録保存は通常システムが得意。';return '子どもの安全や関係者への影響が大きく、人の責任ある判断が必要。'}
function shortName(s){return s.replace('・クラスだより','').replace('・議事録','').replace('・採用広報','')}
const demos={newsletter:['行事予定と季節の話題を集める\n→ 書き出しを考える\n→ 本文を作る\n→ 主任が修正\n→ 園長確認','今月の行事・伝えたいことを箇条書き\n→ AIが園だよりの下書きを作成\n→ 主任が園らしい表現へ修正\n→ 園長確認\n\n例：\n「朝夕は少しずつ秋らしい風を感じるようになりました。今月は運動遊びを通して、友だちと一緒に挑戦する楽しさを大切にしていきます。」'],meeting:['会議中にメモ\n→ 後で読み返す\n→ 決定事項を整理\n→ 担当者へ確認','個人情報を除いた会議メモ\n→ AIが「決定・担当・期限・未決定」に整理\n→ 主任が確認\n\n出力例：\n決定：避難訓練の時間変更\n担当：主任\n期限：9/18\n要確認：保護者案内の配信日'],recruit:['求人票を開く\n→ 前回文をコピー\n→ 条件を修正\n→ 園の魅力を考える','採用条件と園の特徴を入力\n→ 求職者別に求人文を下書き\n→ 事実確認して公開\n\n例：\n「新人を一人にしない」を軸に、1日の流れとフォロー体制を具体的に紹介。'],sns:['写真を選ぶ\n→ 投稿内容を考える\n→ 文章を書く\n→ ハッシュタグを考える','個人を特定できない活動内容を入力\n→ 3案を生成\n→ 園の方針に合う1案を選び修正\n\n例：\n「今日は園庭で秋探し。子どもたちは葉っぱの形や色の違いに夢中でした。」'],parent:['伝える内容を整理\n→ 文章を書く\n→ 強すぎない表現へ直す\n→ 園長・主任確認','伝える事実とお願いを箇条書き\n→ AIが「短く・やわらかく・誤解しにくく」下書き\n→ 必ず職員が事実確認して送信'],plans:['過去資料を見る\n→ 今月のねらいを考える\n→ 文言を整える','前月の振り返りと今月の活動案\n→ AIが下書き候補\n→ 担任が子どもの実態に合わせて修正\n→ 主任確認'],handover:['申し送りを読む\n→ 重要箇所を探す\n→ 次の担当へ説明','個人情報を含めない業務メモ\n→ AIが「今日・要確認・期限」に整理\n→ 職員が確認して共有'],incident:['記録を読む\n→ 類似ケースを探す\n→ 会議用にまとめる','匿名化した記録を分類\n→ 発生場所・時間帯・要因候補を整理\n→ 人が原因と対策を検討'],shift:['希望を集める\n→ 人数条件を確認\n→ Excelで調整','勤務条件はAIチャットよりシフトシステムへ\n→ 条件違反を機械的にチェック\n→ 責任者が最終調整'],billing:['紙・Excel・複数画面で集計','既存ICTの連携を優先\n→ 二重入力を減らす\n→ AIは例外処理の説明補助など限定利用'],complaint:['状況を聞く\n→ 園長・主任が判断\n→ 回答を考える','AIは時系列整理や回答案の比較まで\n→ 事実確認・謝罪・方針決定は園側が行う'],safety:['状況確認\n→ 職員が安全判断\n→ 必要な連絡・対応','ここはAIに任せない\n→ 園の安全手順・専門職・責任者の判断を優先']};
function showDemo(t){const d=demos[t.id]||['今の手順を確認','AIやシステムを使う範囲を整理し、人が確認して完了'];document.getElementById('beforeSample').textContent=d[0];document.getElementById('afterSample').textContent=d[1]}
document.getElementById('restartBtn').addEventListener('click',()=>{form.reset();hours.value=6;hoursOut.textContent='6時間/週';results.style.display='none';form.classList.remove('hidden');document.getElementById('downloadStatus').classList.add('hidden');showStep(1)});
document.getElementById('downloadBtn').addEventListener('click',()=>{if(!lastDiagnosis)return;const d=lastDiagnosis;const lines=[`保育AIチェック 診断メモ`,`対象：${d.name}`,`AI活用余地：${d.score}/100`,`参考：週の削減余地 約${d.saveHours}時間`,`最優先：${d.top.name}`,'','今すぐAIで試す',...d.groups.ai.map(x=>`・${x.name}`),'','AIは補助だけ',...d.groups.assist.map(x=>`・${x.name}`),'','通常システム向き',...d.groups.system.map(x=>`・${x.name}`),'','人が判断する',...d.groups.human.map(x=>`・${x.name}`),'','注意：本結果は無料デモの簡易診断です。園児・保護者等の個人情報は入力せず、実導入前に園のルール・保存先・権限・承認方法を確認してください。'];const blob=new Blob([lines.join('\n')],{type:'text/plain;charset=utf-8'});const a=document.createElement('a');a.href=URL.createObjectURL(blob);a.download='hoiku-ai-check-result.txt';document.body.appendChild(a);a.click();a.remove();setTimeout(()=>URL.revokeObjectURL(a.href),1000);document.getElementById('downloadStatus').classList.remove('hidden')});
showStep(1);
})();